// svelte/src/routes/okuma-listesi/+page.svelte
<main class="flex flex-col items-center justify-between space-y-8">
  <section class="prose w-5/6 mt-8">
    <h1>Okuma Listesi</h1>
    <h2 class="-mt-2">Esin ve Bilgi Kaynakları</h2>
    <ul>
      <li>Ahmet Soysal / Bir Ekolojistin Not Defteri</li>
      <li>Alain de Botton / Felsefenin Tesellisi</li>
      <li>Alan Watts / Mutluluğun Anlamı</li>
      <li>Ali Ayten / Tasavvuf Psikolojisi</li>
      <li>Antonio Damasio / Descartes’ın Yanılgısı</li>
      <li>Aristoteles / Nikomakhos’a Etik</li>
      <li>Arthur Schopenhauer / İnsan Doğası Üzerine</li>
      <li>Arthur Schopenhauer / Yaşam Bilgeliği Üzerine Aforizmalar</li>
      <li>
        Aslı Perker / Hoş Geldin Yabancı, Burada En Büyük Amacımız
        Mutluluktur-Epikür
      </li>
      <li>
        Aslı Perker / Kendisinin Efendisi Olmayan Hiç Kimse Özgür
        Değildir-Epiktetos
      </li>
      <li>Bill Gates / İklim Felaketini Nasıl Önleriz</li>
      <li>Carl Sagan / Kozmos</li>
      <li>Carl Sagan / Soluk Mavi Nokta</li>
      <li>Cemalnur Sargut / Allah’ıma Sefere Çıktım</li>
      <li>Charles Darwin / İnsan ve Hayvanlarda Duyguların İfade Edilmesi</li>
      <li>Charles Darwin / İnsanın Türeyişi</li>
      <li>Charles Darwin / Türlerin Kökeni</li>
      <li>
        Christopher Peterson-Martin Seligman / Character Strengths and Virtues:
        A Handbook and Classification
      </li>
      <li>Cicero / Dostluk Üzerine-De Amicitia</li>
      <li>Cicero / Yaşlı Cato ve Yaşlılık Üzerine</li>
      <li>Damon Young / Bahçede Felsefe</li>
      <li>Dan Buettner / Mavi Bölgeler</li>
      <li>Daniel Chamovitz / Bitkilerin Bildikleri</li>
      <li>Doğan Cüceloğlu / Var mısın? Güçlü Bir Yaşam İçin Öneriler</li>
      <li>Dr. Murat Kınıkoğlu / Vegan Beslenme</li>
      <li>Edward Osborne Wilson / Biophilia</li>
      <li>Edward Osborne Wilson / Doğanın Gizli Bahçesi</li>
      <li>Emanuele Coccia / Bitkilerin Yaşamı-Bir Karışım Metafiziği</li>
      <li>Engin Geçtan / Hayat</li>
      <li>Engin Geçtan / İnsan Olmak</li>
      <li>Engin Geçtan / Rastgele Ben</li>
      <li>Epiktetos / İçsel Huzur İyi Yaşamın Kapısını Açar</li>
      <li>Erich Fromm / İnsandaki Yıkıcılığın Kökenleri</li>
      <li>Farabi / Mutluluğun Kazanılması</li>
      <li>Ferhat Jak İçöz / Kendin Olmanın Dayanılmaz Hafifliği</li>
      <li>Feza Karakaş / Mutluluk Projesi</li>
      <li>Francis Bacon / Denemeler</li>
      <li>Franz Kafka / Dava</li>
      <li>Frederic Gros / Yürümenin Felsefesi</li>
      <li>Friedrich Nietzsche / Böyle Buyurdu Zerdüşt</li>
      <li>George Monbiot / Yaban Yaşam</li>
      <li>Gülin Yücel-Levent Kurnaz / Yeni Gerçeğimiz Sürdürülebilirlik</li>
      <li>Gündüz Vassaf / Cehenneme Övgü</li>
      <li>Halil Cibran / Ermiş</li>
      <li>Hector Garcia-Francesc Miralles / Ikigai</li>
      <li>Henry David Thoreau / Nerede ve Ne İçin Yaşadım</li>
      <li>Henry David Thoreau / Walden-Ormanda Yaşam</li>
      <li>Henry David Thoreau / Yürümek</li>
      <li>Hermann Hesse / Ağaçlar</li>
      <li>Hermann Hesse / Öldürmeyeceksin</li>
      <li>H. G. Wells / Zaman Makinesi</li>
      <li>İhsan Fazlıoğlu / Kendini Aramak</li>
      <li>İlber Ortaylı / Bir Ömür Nasıl Yaşanır</li>
      <li>İlber Ortaylı / İnsan Geleceğini Nasıl Kurar</li>
      <li>James Joyce / Ulysses</li>
      <li>Jason Hickel / Çoğu Zarar Azı Karar-Dünyayı Küçülme Kurtaracak</li>
      <li>Jean-Jacques Rousseau / Eşitsizliğin Kökeni</li>
      <li>Jean-Jacques Rousseau / Yalnız Gezer’in Düşleri</li>
      <li>Jonathan Balcombe / Balıkların Bildikleri</li>
      <li>Jonathan Safran Foer / Hayvan Yemek</li>
      <li>John Fowles / Ağaçlar</li>
      <li>
        Kiraz Özdoğan, M. Fatih Tatari, Ali Bilgin / İnsan Hayvan ve Ötesi
      </li>
      <li>
        Kolektif-Editör Samet Kılıç / Halkbilimi Bağlamında Türkiye’de Yeme-İçme
        Kültürü
      </li>
      <li>Laozi / Yol ve Erdem</li>
      <li>Marc Bekoff / Hayvanların Duygusal Dünyası</li>
      <li>Marcus Aurelius / Kendime Düşünceler</li>
      <li>Matt Haig / İnsanlar</li>
      <li>Matthieu Ricard / Mutluluğa Övgü</li>
      <li>Maureen Gaffney / Your One Wild and Precious Life</li>
      <li>Mesud Topal / Var mısın ki Yok Olmaktan KorkuyorsunFarabi</li>
      <li>
        Metehan Tanyıldız / İlim Anavatanımızdır, Cehalet ise Yabancı Bir
        Yer-İbni Rüşd
      </li>
      <li>Michel Serres / Doğayla Sözleşme</li>
      <li>Mihaly Csikszentmihalyi / Akış-Mutluluk Bilimi</li>
      <li>Montaigne / Denemeler</li>
      <li>Nermi Uygur / Yaşama Felsefesi</li>
      <li>Norman Hampson / Aydınlanma Çağı</li>
      <li>Öykü Yaman, Emine Aksoydan / Sürdürülebilir Yaşam Rehberi</li>
      <li>
        Özlem Küskü / Dışa Bakan Rüya Görür İçe Bakan Uyanır-Carl Gustav Jung
      </li>
      <li>Peter Singer / Hayvan Özgürleşmesi</li>
      <li>Peter Singer / Neden Vegan</li>
      <li>Peter Wohlleben / Ağaçların Gizli Yaşamı</li>
      <li>Peter Wohlleben / Hayvanların Gizli Yaşamı</li>
      <li>Platon / Diyaloglar</li>
      <li>Ralph Waldo Emerson / Doğa</li>
      <li>Ralph Waldo Emerson / Nefse İtimat</li>
      <li>Richard Louv / Doğadaki Son Çocuk</li>
      <li>Sait Faik Abasıyanık / Son Kuşlar</li>
      <li>Samuel Beckett / Aşksız İlişkiler</li>
      <li>Seneca / Yaşamın Kısalığı Üzerine</li>
      <li>Sinan Canan / İFA-İnsanın Fabrika Ayarları-1. Kitap</li>
      <li>Stefan Zweig / Montaigne: Her Şeyin Birazı, Hiçbir Şeyin Hepsi</li>
      <li>Stefano Mancuso / Bitki Ulusu</li>
      <li>Stuart Walton / A Natural History of Human Emotions</li>
      <li>Viktor Emil Frankl / İnsanın Anlam Arayışı</li>
      <li>Walther Kranz / Antik Felsefe</li>
      <li>Wilhelm Schmid / Dokunmak Üstüne</li>
      <li>Wilhelm Schmid / Kendiyle Dost Olmak</li>
      <li>Wilhelm Schmid / Mutsuz Olmak: Bir Yüreklendirme</li>
      <li>Wilhelm Schmid / Sakin Olmak</li>
      <li>Yaşar Kemal / İnce Memed 3</li>
      <li>Yuval Noah Harari / Hayvanlardan Tanrılara-Sapiens</li>
      <li>Zülal Kalkandelen / Vegan Devrimi ve Hayvan Özgürlüğü</li>
      <li>Zygmunt Bauman / Yaşam Sanatı</li>
    </ul>
  </section>
</main>

// app/okuma-listesi/page.tsx
export default function ReadingList() {
  return (
    <main className="flex flex-col items-center justify-between space-y-8">
      <section className="prose w-5/6 mt-8">
        <h1>Okuma Listesi</h1>
        <h2 className="-mt-2">Esin ve Bilgi Kaynakları</h2>
        <ul>
          <li>Ahmet Soysal / Bir Ekolojistin Not Defteri</li>
          <li>Alain de Botton / Felsefenin Tesellisi</li>
          <li>Alan Watts / Mutluluğun Anlamı</li>
          <li>Ali Ayten / Tasavvuf Psikolojisi</li>
          <li>Antonio Damasio / Descartes’ın Yanılgısı</li>
          <li>Aristoteles / Nikomakhos’a Etik</li>
          <li>Arthur Schopenhauer / İnsan Doğası Üzerine</li>
          <li>Arthur Schopenhauer / Yaşam Bilgeliği Üzerine Aforizmalar</li>
          <li>
            Aslı Perker / Hoş Geldin Yabancı, Burada En Büyük Amacımız
            Mutluluktur-Epikür
          </li>
          <li>
            Aslı Perker / Kendisinin Efendisi Olmayan Hiç Kimse Özgür
            Değildir-Epiktetos
          </li>
          <li>Bill Gates / İklim Felaketini Nasıl Önleriz</li>
          <li>Carl Sagan / Kozmos</li>
          <li>Carl Sagan / Soluk Mavi Nokta</li>
          <li>Cemalnur Sargut / Allah’ıma Sefere Çıktım</li>
          <li>
            Charles Darwin / İnsan ve Hayvanlarda Duyguların İfade Edilmesi
          </li>
          <li>Charles Darwin / İnsanın Türeyişi</li>
          <li>Charles Darwin / Türlerin Kökeni</li>
          <li>
            Christopher Peterson-Martin Seligman / Character Strengths and
            Virtues: A Handbook and Classification
          </li>
          <li>Cicero / Dostluk Üzerine-De Amicitia</li>
          <li>Cicero / Yaşlı Cato ve Yaşlılık Üzerine</li>
          <li>Damon Young / Bahçede Felsefe</li>
          <li>Dan Buettner / Mavi Bölgeler</li>
          <li>Daniel Chamovitz / Bitkilerin Bildikleri</li>
          <li>Doğan Cüceloğlu / Var mısın? Güçlü Bir Yaşam İçin Öneriler</li>
          <li>Dr. Murat Kınıkoğlu / Vegan Beslenme</li>
          <li>Edward Osborne Wilson / Biophilia</li>
          <li>Edward Osborne Wilson / Doğanın Gizli Bahçesi</li>
          <li>Emanuele Coccia / Bitkilerin Yaşamı-Bir Karışım Metafiziği</li>
          <li>Engin Geçtan / Hayat</li>
          <li>Engin Geçtan / İnsan Olmak</li>
          <li>Engin Geçtan / Rastgele Ben</li>
          <li>Epiktetos / İçsel Huzur İyi Yaşamın Kapısını Açar</li>
          <li>Erich Fromm / İnsandaki Yıkıcılığın Kökenleri</li>
          <li>Farabi / Mutluluğun Kazanılması</li>
          <li>Ferhat Jak İçöz / Kendin Olmanın Dayanılmaz Hafifliği</li>
          <li>Feza Karakaş / Mutluluk Projesi</li>
          <li>Francis Bacon / Denemeler</li>
          <li>Franz Kafka / Dava</li>
          <li>Frederic Gros / Yürümenin Felsefesi</li>
          <li>Friedrich Nietzsche / Böyle Buyurdu Zerdüşt</li>
          <li>George Monbiot / Yaban Yaşam</li>
          <li>Gülin Yücel-Levent Kurnaz / Yeni Gerçeğimiz Sürdürülebilirlik</li>
          <li>Gündüz Vassaf / Cehenneme Övgü</li>
          <li>Halil Cibran / Ermiş</li>
          <li>Hector Garcia-Francesc Miralles / Ikigai</li>
          <li>Henry David Thoreau / Nerede ve Ne İçin Yaşadım</li>
          <li>Henry David Thoreau / Walden-Ormanda Yaşam</li>
          <li>Henry David Thoreau / Yürümek</li>
          <li>Hermann Hesse / Ağaçlar</li>
          <li>Hermann Hesse / Öldürmeyeceksin</li>
          <li>H. G. Wells / Zaman Makinesi</li>
          <li>İhsan Fazlıoğlu / Kendini Aramak</li>
          <li>İlber Ortaylı / Bir Ömür Nasıl Yaşanır</li>
          <li>İlber Ortaylı / İnsan Geleceğini Nasıl Kurar</li>
          <li>James Joyce / Ulysses</li>
          <li>
            Jason Hickel / Çoğu Zarar Azı Karar-Dünyayı Küçülme Kurtaracak
          </li>
          <li>Jean-Jacques Rousseau / Eşitsizliğin Kökeni</li>
          <li>Jean-Jacques Rousseau / Yalnız Gezer’in Düşleri</li>
          <li>Jonathan Balcombe / Balıkların Bildikleri</li>
          <li>Jonathan Safran Foer / Hayvan Yemek</li>
          <li>John Fowles / Ağaçlar</li>
          <li>
            Kiraz Özdoğan, M. Fatih Tatari, Ali Bilgin / İnsan Hayvan ve Ötesi
          </li>
          <li>
            Kolektif-Editör Samet Kılıç / Halkbilimi Bağlamında Türkiye’de
            Yeme-İçme Kültürü
          </li>
          <li>Laozi / Yol ve Erdem</li>
          <li>Marc Bekoff / Hayvanların Duygusal Dünyası</li>
          <li>Marcus Aurelius / Kendime Düşünceler</li>
          <li>Matt Haig / İnsanlar</li>
          <li>Matthieu Ricard / Mutluluğa Övgü</li>
          <li>Maureen Gaffney / Your One Wild and Precious Life</li>
          <li>Mesud Topal / Var mısın ki Yok Olmaktan KorkuyorsunFarabi</li>
          <li>
            Metehan Tanyıldız / İlim Anavatanımızdır, Cehalet ise Yabancı Bir
            Yer-İbni Rüşd
          </li>
          <li>Michel Serres / Doğayla Sözleşme</li>
          <li>Mihaly Csikszentmihalyi / Akış-Mutluluk Bilimi</li>
          <li>Montaigne / Denemeler</li>
          <li>Nermi Uygur / Yaşama Felsefesi</li>
          <li>Norman Hampson / Aydınlanma Çağı</li>
          <li>Öykü Yaman, Emine Aksoydan / Sürdürülebilir Yaşam Rehberi</li>
          <li>
            Özlem Küskü / Dışa Bakan Rüya Görür İçe Bakan Uyanır-Carl Gustav
            Jung
          </li>
          <li>Peter Singer / Hayvan Özgürleşmesi</li>
          <li>Peter Singer / Neden Vegan</li>
          <li>Peter Wohlleben / Ağaçların Gizli Yaşamı</li>
          <li>Peter Wohlleben / Hayvanların Gizli Yaşamı</li>
          <li>Platon / Diyaloglar</li>
          <li>Ralph Waldo Emerson / Doğa</li>
          <li>Ralph Waldo Emerson / Nefse İtimat</li>
          <li>Richard Louv / Doğadaki Son Çocuk</li>
          <li>Sait Faik Abasıyanık / Son Kuşlar</li>
          <li>Samuel Beckett / Aşksız İlişkiler</li>
          <li>Seneca / Yaşamın Kısalığı Üzerine</li>
          <li>Sinan Canan / İFA-İnsanın Fabrika Ayarları-1. Kitap</li>
          <li>
            Stefan Zweig / Montaigne: Her Şeyin Birazı, Hiçbir Şeyin Hepsi
          </li>
          <li>Stefano Mancuso / Bitki Ulusu</li>
          <li>Stuart Walton / A Natural History of Human Emotions</li>
          <li>Viktor Emil Frankl / İnsanın Anlam Arayışı</li>
          <li>Walther Kranz / Antik Felsefe</li>
          <li>Wilhelm Schmid / Dokunmak Üstüne</li>
          <li>Wilhelm Schmid / Kendiyle Dost Olmak</li>
          <li>Wilhelm Schmid / Mutsuz Olmak: Bir Yüreklendirme</li>
          <li>Wilhelm Schmid / Sakin Olmak</li>
          <li>Yaşar Kemal / İnce Memed 3</li>
          <li>Yuval Noah Harari / Hayvanlardan Tanrılara-Sapiens</li>
          <li>Zülal Kalkandelen / Vegan Devrimi ve Hayvan Özgürlüğü</li>
          <li>Zygmunt Bauman / Yaşam Sanatı</li>
        </ul>
      </section>
    </main>
  );
}
